config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'project#welcome'
  get '/start', to: 'project#index'
  post '/new_project', to: 'project#new_project'
  delete '/destroy_project/:projectId', to: 'project#destroy_project',as: 'destroy_project'
  get '/dashboard/:id', to: 'dashboard#index', as: 'dashboard'
  post '/move_to_sprint/:cardId/:boardId', to: 'card#move_to_sprint'
  post '/move_to_planned/:card_id', to: 'sprint_card#move_to_planned'
  post '/new_card', to: 'card#new_card'
  post '/add_user/:projectId/:userId', to: 'project#add_user'
  post '/rename/:id', to: 'card#rename'
  get 'sprint/:id', to: 'sprint#index', as: 'sprint'
  get '/change_sprint_board/:cardId/:board_title', to: 'sprint_card#change_board'
  get '/change_board/:cardId/:boardId', to: 'dashboard#change_board'
  post '/change_board_and_delete/:cardId/:boardId', to: 'dashboard#change_board_and_delete'
  post '/update_sprint_card/:id', to: 'sprint_card#update'
  post '/update_card/:id', to: 'card#update'
  post '/sprint_card_done/:cardId', to: 'sprint_card#done'
  get '/check_estimations/:cardId/:round_number', to: 'sprint_card#check_estimations'
  get '/check_comments/:cardId/:round_number', to: 'sprint_card#check_comments'
  get '/get_projects', to: 'project#get_projects'
  get '/get_cards/:board_id', to: 'dashboard#get_cards'
  get '/get_sprint_cards/:sprint_board_id', to: 'sprint#get_sprint_cards'
  get '/get_users/:project_id', to: 'project#get_users'
  get '/get_available_users/:project_id', to: 'project#get_available_users'
  post '/add_round/:card_id/:round_number', to: 'sprint_card#add_round'
  post '/add_card_round/:card_id/:round_number', to: 'card#add_card_round'
  get '/card_assets/:card_id', to: 'sprint_card#card_assets'
  get '/user_count/:project_id', to: 'project#user_count'
  get '/update_comments/:round_id', to: 'sprint_card#update_comments'
  post '/update_card_comments/:round_id', to: 'card#update_card_comments'
  post '/estimate/:card_id', to: 'sprint_card#estimate'
  post '/estimate_card/:card_id', to: 'card#estimate'
  get '/check_estimation_done/:card_id', to: 'sprint_card#check_estimation_done'
  post '/update_options/:card_id', to: 'sprint_card#update_options'
  post '/update_work_done/:card_id', to: 'sprint_card#update_work_done'
  get '/role_management', to: 'project#role_management', as: 'role'
  post '/change_role', to: 'project#change_role'
  post '/register_for_card/:card_id', to: 'sprint_card#register_for_card'
  post '/new_sprint_card', to: 'sprint_card#new_sprint_card'
  delete '/delete_sprint_card/:card_id', to: 'sprint_card#delete_sprint_card'
  delete '/delete_card/:card_id', to: 'card#delete_card'
  post '/update_request/:card_id', to: 'sprint_card#update_request'
  post '/update_prio', to: 'sprint_card#update_prio'
  get '/update_retro', to: 'sprint_card#update_retro'
  get '/render_charts', to: 'dashboard#render_charts'
  get '/assets/:card_id', to: 'card#assets'
  post '/update_card_options/:card_id', to: 'card#update_card_options'
  get '/render_sb', to: 'dashboard#render_sb'
  get '/render_roadmap', to: 'roadmap#render_roadmap'
  get '/render_participants', to: 'dashboard#render_participants'
  delete '/remove_user', to: 'dashboard#remove_user'
  post '/add_row', to: 'roadmap#add_row'
  post '/add_roadmap_item', to: 'roadmap#add_roadmap_item'
  delete '/delete_roadmap_item', to: 'roadmap#delete_roadmap_item'
  delete '/delete_roadmap_row', to: 'roadmap#delete_roadmap_row'
  post '/end_sprint', to: 'sprint#end_sprint'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :dashboard
  has_many :cards
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :board
  belongs_to :sprint, optional: true
  has_many :sprint_cards
  has_many :estimation_rounds
  has_many :acceptance_criteriums
end

app/models/change_request.rb
class ChangeRequest < ApplicationRecord
  belongs_to :sprint_card
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :project
  has_many :boards
  has_many :sprints
  has_many :statistics
  has_many :roadmap_rows
end

app/models/estimated_work.rb
class EstimatedWork < ApplicationRecord
  belongs_to :estimation_round
end

app/models/estimation_round.rb
class EstimationRound < ApplicationRecord
  belongs_to :sprint_card, optional: true
  belongs_to :card, optional: true
  has_many :estimated_works
  has_many :work_comments

end

app/models/project.rb
class Project < ApplicationRecord
  has_one :dashboard
  has_and_belongs_to_many :users
end

app/models/roadmap_item.rb
class RoadmapItem < ApplicationRecord
  belongs_to :roadmap_row
end

app/models/roadmap_row.rb
class RoadmapRow < ApplicationRecord
  belongs_to :dashboard
  has_many :roadmap_items
end

app/models/sprint.rb
class Sprint < ApplicationRecord
  belongs_to :dashboard
  has_many :sprint_boards
  has_many :cards
  has_one :statistic
  has_many :sprint_retro_comments
end

app/models/sprint_board.rb
class SprintBoard < ApplicationRecord
  belongs_to :sprint
  has_many :sprint_cards
end

app/models/sprint_card.rb
class SprintCard < ApplicationRecord
  has_many :estimation_rounds
  belongs_to :sprint_board, optional: true
  belongs_to :card, optional: true
  has_many :change_requests
end

app/models/statistic.rb
class Statistic < ApplicationRecord
  belongs_to :sprint, optional: true
  belongs_to :dashboard, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :projects
  enum role: [:stakeholder, :product_owner, :scrum_master, :scrum_team]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :stakeholder
  end
end

app/models/work_comment.rb
class WorkComment < ApplicationRecord
  belongs_to :estimation_round
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController

  def welcome
  end
  def index
  end
  def role_management
    @users = User.all
  end
  def change_role
    user = User.find(params[:user_id])
    user.update(role: params[:role])
  end
  def add_user
    project = Project.find(params[:projectId])
    user = User.find(params[:userId])
    project.users << user
  end
  def get_users
    project = Project.find(params[:project_id])
    render json: project.users
  end
  def get_available_users
    project = Project.find(params[:project_id])
    users = User.all - project.users
    render json: users
  end

  def new_project
    project = Project.new(title: params[:title])

    project.build_dashboard
    project.dashboard.boards.build(title: "Product Backlog")
    project.dashboard.boards.build(title: "Aktueller Sprint")
    project.dashboard.sprints.build(active: true, started: false, finished: false)
    project.dashboard.sprints.last.sprint_boards.build(title: "Sprint Backlog")
    project.dashboard.sprints.last.sprint_boards.build(title: "Planning")
    project.dashboard.sprints.last.sprint_boards.build(title: "In Work")
    project.dashboard.sprints.last.sprint_boards.build(title: "Code Review")
    project.dashboard.sprints.last.sprint_boards.build(title: "Done")
    project.save
    current_user.projects << project
  end

  def get_projects
    projects = current_user.projects
    render json: projects
  end

  def destroy_project
    project = Project.find(params[:projectId])
    project.destroy
    render 'project/welcome'
  end

  def user_count
    users = Project.find(params[:project_id]).users.where(role: "scrum_team").count
    render json: {user_count: users}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/roadmap_helper.rb
module RoadmapHelper
end

app/helpers/sprint_helper.rb
module SprintHelper
end

app/views/project/_index.html.erb
<div id ="index-wrapper">

  <div class="container-fluid">
    <div class="row">
      <% if current_user.product_owner? %>
      <%=	 link_to 'Rollenverwaltung', role_path, class: 'btn btn-success' %>
      <% end %>
      <div id="projects"></div>
      <div class="col-sm-3" style="margin-top: 2em">
        <%	 if current_user.product_owner? %>
        <div class="well well-lg shadow" data-toggle="modal" data-target="#new-project-modal">Neues Projekt...</div>
        <div class="modal fade" id="new-project-modal" role="dialog">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Neues Projekt anlegen</h4>
              </div>
              <div class="modal-body">
                <%= form_tag("/new_project", method: "post", class: "project-form") do %>
                    <%= label_tag(:title, "Titel:") %>
                    <%= text_field_tag(:title) %>
                    <br><br><br>
                    <%= submit_tag("Anlegen", class:"btn btn-success", id: "confirm-button") %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

<script>

  $(document).ready(function() {
    $("#projects").children().remove();
    getProjects();
  });


  $(".project-form").submit( function (e) {
    e.preventDefault();
    var form = $(this);
    var title = form.children("#title").val();
    $(".dropdown").hide();
    $.ajax({
      type: "POST",
      url: '/new_project',
      data: { title: title },
      success: function(data, textStatus, xhr) {
        $('#new-project-modal').modal('toggle');
        $("#projects").children().remove();
        getProjects();
      }
    });

  });

  function getProjects() {

    $.ajax({
      type: "GET",
      url: '/get_projects',
      success: function(data) {

        for (var x = 0; x < data.length; x++) {
          var content =  '<div class="col-sm-3" style="margin-top: 2em">'
          content += '<a href="/dashboard/'+ data[x].id +'">'
          content += '<div class="well well-lg shadow" style="background-color: palegreen; text-align: center">'
          content += data[x].title + '</div></a></div>';
          $(content).appendTo("#projects");
        }
      }
    });
  };


</script>

app/views/project/_start.html.erb
<div id="wrapper-index" class="text-center">
  <h1>Willkommen</h1>
  <p>
    <strong>Scrum Tool</strong> unterstützt Sie bei der Planung Ihrer Projekte unter dem SCRUM Paradigma
  </p>
</div>

app/views/project/index.html.erb
<div id ="index-wrapper">

  <div class="container-fluid">
    <div class="row">

      <div id="projects"></div>

      <div class="col-sm-3" style="margin-top: 2em">

        <div class="well well-lg shadow" data-toggle="modal" data-target="#new-project-modal">Neues Projekt...</div>

        <div class="modal fade" id="new-project-modal" role="dialog">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Neues Projekt anlegen</h4>
              </div>
              <div class="modal-body">
                <%= form_tag("/new_project", method: "post", class: "project-form") do %>
                    <%= label_tag(:title, "Titel:") %>
                    <%= text_field_tag(:title) %>
                    <br><br><br>
                    <%= submit_tag("Anlegen", class:"btn btn-success", id: "confirm-button") %>
                <% end %>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

</div>

<script>

  $(document).ready(function() {
    getProjects();
  });


  $(".project-form").submit( function (e) {
    e.preventDefault();
    var form = $(this);
    var title = form.children("#title").val();
    $(".dropdown").hide();
    $.ajax({
      type: "POST",
      url: '/new_project',
      data: { title: title },
      success: function(data, textStatus, xhr) {
        $('#new-project-modal').modal('toggle');
        getProjects();
      }
    });

  });

  function getProjects() {

    $.ajax({
      type: "GET",
      url: '/get_projects',
      success: function(data) {

        for (var x = 0; x < data.length; x++) {
          var content =  '<div class="col-sm-3" style="margin-top: 2em">'
          content += '<a href="/dashboard/'+ data[x].id +'">'
          content += '<div class="well well-lg shadow" style="background-color: palegreen; text-align: center">'
          content += data[x].title + '</div></a></div>';
          $(content).appendTo("#projects");
        }
      }
    });
  };


</script>

app/views/project/role_management.html.erb
<%	 if current_user.product_owner? %>
    <div class="container-fluid">
      <h2>Nutzerverwaltung</h2>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Rolle</th>
          <th>Neue Rolle</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <%	 @users.each do |f| %>
            <tr>
              <td><%=	 f.username %></td>
              <td><%=	 f.email %></td>
              <td id="role<%= f.id %>"><%=	 f.role %></td>
              <td><%=	 select("user_select", f.id , %w[stakeholder product_owner scrum_master scrum_team], {}, { index: nil }) %></td>
              <td><button type="button" class="btn btn-default" id="button<%= f.id %>" onclick="update(<%= f.id %>)">Speichern</button></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
<% end %>

<script>
  function update(userId) {
    var selection = $('#user_select__'+userId).val();
    var confirmed = confirm('Wirklich ändern?');
    if(confirmed) {
      $.ajax({
        type: "POST",
        url: '/change_role',
        data: { user_id: userId, role: selection },
        success: function(data) {
          $('#role'+userId).text(selection);
        }
      });
    }
  }
</script>

app/views/project/welcome.html.erb
<%	 if user_signed_in? %>
<%=	 render 'project/index' %>
<%	 else %>
<%=	 render 'project/start' %>
<%	 end %>